<?php
/**
 * @file
 * Code for the module.
 */

/**
 * Implements hook_menu().
 */
function wetkit_bootstrapx_menu() {
  $items = array();
  $items['admin/config/user-interface/ember-support'] = array(
    'title' => 'Ember Support',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wetkit_bootstrapx_admin_form'),
    'access arguments' => array('administer site configuration'),
    'description' => 'Allows administrators to configure Ember Support.',
  );
  return $items;
}

/**
 * Administrative settings for the module add-ons.
 */
function wetkit_bootstrapx_admin_form($form, $form_state) {

  // Checkbox to remove the Panels IPE css.
  $form['wetkit_bootstrapx_panels_ipe_css'] = array(
    '#type' => 'checkbox',
    '#title' => t('Override default Panels IPE styles'),
    '#description' => t('Ember Support overrides these styles by default.'),
    '#default_value' => variable_get('wetkit_bootstrapx_panels_ipe_css', TRUE),
  );
  // If Panels IPE is not enabled, disable the settings.
  if (!module_exists('panels_ipe')) {
    $form['wetkit_bootstrapx_panels_ipe_css']['#disabled'] = TRUE;
    variable_del('wetkit_bootstrapx_panels_ipe_css');
  }

  // Checkbox to remove the Panels modal css.
  $form['wetkit_bootstrapx_panels_modal_css'] = array(
    '#type' => 'checkbox',
    '#title' => t('Override Panels modal styles'),
    '#description' => t('Ember Support overrides these styles by default.'),
    '#default_value' => variable_get('wetkit_bootstrapx_panels_modal_css', TRUE),
  );
  // If Panels is not enabled, disable the settings.
  if (!module_exists('panels')) {
    $form['wetkit_bootstrapx_panels_modal_css']['#disabled'] = TRUE;
    variable_del('wetkit_bootstrapx_panels_modal_css');
  }

  // Checkbox to remove the Panopoly Magic css.
  $form['wetkit_bootstrapx_panopoly_magic_css'] = array(
      '#type' => 'checkbox',
      '#title' => t('Override Panopoly Magic styles'),
      '#description' => t('Ember Support overrides these styles by default.'),
      '#default_value' => variable_get('wetkit_bootstrapx_panopoly_magic_css', TRUE),
      );
  // If Panopoly Magic is not enabled, disable the settings.
  if (!module_exists('panopoly_magic')) {
    $form['wetkit_bootstrapx_panopoly_magic_css']['#disabled'] = TRUE;
    variable_del('wetkit_bootstrapx_panopoly_magic_css');
  }
  return system_settings_form($form);
}

/**
 * Implements hook_css_alter().
 */
function wetkit_bootstrapx_css_alter(&$css) {

  $ember_path = drupal_get_path('module', 'wetkit_bootstrapx');

  // Override Panels modal styles by default.
  if (module_exists('panels') && variable_get('wetkit_bootstrapx_panels_modal_css', TRUE) == TRUE) {
    // Do nothing. The css is set in Ember Support's .info file.
  }
  else {
    // Remove Ember Support's Panels modal styles.
    unset($css[$ember_path . '/css/ember-ctools.css']);
    unset($css[$ember_path . '/css/ember-modal.css']);
  }

  // Override Panels IPE styles by default. d
  if (module_exists('panels_ipe') && variable_get('wetkit_bootstrapx_panels_ipe_css', TRUE) == TRUE) {
    // Remove the default Panels IPE css.
    $path = drupal_get_path('module', 'panels_ipe');
    unset($css[$path . '/css/panels_ipe.css']);
  }
  else {
    // Remove Ember Support's Panels IPE styles.
    unset($css[$ember_path . '/css/ember-panels-ipe.css']);
  }

  // Override Panopoly Magic styles by default.
  if (module_exists('panopoly_magic') && variable_get('wetkit_bootstrapx_panopoly_magic_css', TRUE) == TRUE) {
    // Remove css set by default in Panopoly Magic's .info file.
    $path = drupal_get_path('module', 'panopoly_magic');
    unset($css[$path . '/css/panopoly-magic.css']);
    unset($css[$path . '/css/panopoly-modal.css']);
  }

}

