<?php

/**
 * Implements hook_ctools_plugin_directory().
 * @param $module
 * @param $plugin
 * @return string
 */
function wetkit_bootstrapx_ctools_plugin_directory($module, $plugin) {
  if ($module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_preprocess_panels_pane().
 */
function wetkit_bootstrapx_preprocess_panels_pane(&$vars) {
  $pane_id = $vars['pane']->pid;
  $pane_title = &drupal_static($pane_id . '_title');
  $pane_title = $vars['title'];

  drupal_add_js(drupal_get_path('module', 'wetkit_bootstrapx') . '/js/horizontal_tabs.js', 'file');
  drupal_add_css(drupal_get_path('module', 'wetkit_bootstrapx') . '/css/horizontal_tabs.css', 'file');
}

/**
 * Implements hook_view_block_alter().
 */
function wetkit_bootstrapx_block_view_workbench_block_alter(&$data, $block) {
  $items = module_invoke_all('workbench_block');
  if (empty($items)) {
    return;
  }
  $data = array(
    'subject' => '',
    'content' => array(
      '#markup' => theme('container', array('element' => array(
      	'#children' => "<a class=\"close\" data-dismiss=\"alert\" href=\"#\">&times;</a>\n" . implode('<br />', $items),
      	'#attributes' => array('class' => 'alert alert-block alert-info')))),
    ),
  );
  return $data;
}

/**
 * Implements hook_admin_paths_alter().
 */
function wetkit_bootstrapx_admin_paths_alter(&$paths) {
  // Render following pages in Bootstrap theme.
  $paths['admin/appearance/*'] = FALSE;
  $paths['admin/advanced_help'] = FALSE;
  $paths['admin/advanced_help/*'] = FALSE;
  $paths['admin/content'] = FALSE;
  $paths['admin/content/*'] = FALSE;
  $paths['admin/config'] = FALSE;
  $paths['admin/config/*'] = FALSE;
  $paths['admin/dashboard'] = FALSE;
  $paths['admin/dashboard/*'] = FALSE;
  $paths['admin/people'] = FALSE;
  $paths['admin/people/*'] = FALSE;
  $paths['admin/structure'] = FALSE;
  $paths['admin/structure/pages'] = FALSE;
  $paths['admin/structure/pages/*'] = FALSE;
  $paths['admin/wetkit'] = FALSE;
  $paths['admin/wetkit/*'] = FALSE;
  $paths['admin/workbench'] = FALSE;
  $paths['admin/workbench/*'] = FALSE;
  $paths['admin/reports'] = FALSE;
  $paths['block/*'] = FALSE;
  $paths['block/*/edit'] = FALSE;
  $paths['block/*/edit/*'] = FALSE;
  $paths['media/*/edit'] = FALSE;
  $paths['media/*/edit/*'] = FALSE;
  $paths['user/*/*'] = FALSE;
}
